#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# exec celery -A config.celery_app worker -l INFO
celery -A config.celery_app worker --concurrency=1 -l INFO
# celery -A config.celery_app worker --concurrency=1 --max-tasks-per-child=50 -l INFO
