# Generated by Django 5.0 on 2025-05-22 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('attorney', 'Attorney'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
